#
# Imports
#

from __future__ import annotations

from classes.chunks.Fence2Chunk import Fence2Chunk
from classes.chunks.FenceChunk import FenceChunk
from classes.chunks.HistoryChunk import HistoryChunk
from classes.chunks.ImageChunk import ImageChunk
from classes.chunks.ImageDataChunk import ImageDataChunk
from classes.chunks.IndexListChunk import IndexListChunk
from classes.chunks.MeshChunk import MeshChunk
from classes.chunks.OldPrimitiveGroupChunk import OldPrimitiveGroupChunk
from classes.chunks.PathChunk import PathChunk
from classes.chunks.PositionListChunk import PositionListChunk
from classes.chunks.ShaderChunk import ShaderChunk
from classes.chunks.ShaderColourParameterChunk import ShaderColourParameterChunk
from classes.chunks.ShaderFloatParameterChunk import ShaderFloatParameterChunk
from classes.chunks.ShaderIntegerParameterChunk import ShaderIntegerParameterChunk
from classes.chunks.ShaderTextureParameterChunk import ShaderTextureParameterChunk
from classes.chunks.StaticEntityChunk import StaticEntityChunk
from classes.chunks.TextureChunk import TextureChunk
from classes.chunks.UVListChunk import UVListChunk
from classes.chunks.ColourListChunk import ColourListChunk
from classes.chunks.VertexShaderChunk import VertexShaderChunk
from classes.chunks.BoundingBoxChunk import BoundingBoxChunk
from classes.chunks.BoundingSphereChunk import BoundingSphereChunk
from classes.chunks.StaticPhysChunk import StaticPhysChunk
from classes.chunks.CollisionObjectChunk import CollisionObjectChunk
from classes.chunks.CollisionVolumeChunk import CollisionVolumeChunk
from classes.chunks.CollisionOrientedBoundingBoxChunk import CollisionOrientedBoundingBoxChunk
from classes.chunks.CollisionVectorChunk import CollisionVectorChunk
from classes.chunks.CollisionCylinderChunk import CollisionCylinderChunk
from classes.chunks.CollisionSphereChunk import CollisionSphereChunk
from classes.chunks.CollisionObjectAttributeChunk import CollisionObjectAttributeChunk
from classes.chunks.CollisionEffectChunk import CollisionEffectChunk
from classes.chunks.CollisionAxisAlignedBoundingBoxChunk import CollisionAxisAlignedBoundingBoxChunk
from classes.chunks.RenderStatusChunk import RenderStatusChunk
from classes.chunks.InstanceListChunk import InstanceListChunk
from classes.chunks.InstStatEntityChunk import InstStatEntityChunk
from classes.chunks.InstStatPhysChunk import InstStatPhysChunk
from classes.chunks.DynaPhysChunk import DynaPhysChunk
from classes.chunks.OldScenegraphRootChunk import OldScenegraphRootChunk
from classes.chunks.OldScenegraphBranchChunk import OldScenegraphBranchChunk
from classes.chunks.OldScenegraphSortOrderChunk import OldScenegraphSortOrderChunk
from classes.chunks.OldScenegraphTransformChunk import OldScenegraphTransformChunk
from classes.chunks.OldScenegraphDrawableChunk import OldScenegraphDrawableChunk
from classes.chunks.ScenegraphChunk import ScenegraphChunk
from classes.chunks.PhysicsObjectChunk import PhysicsObjectChunk
from classes.chunks.PhysicsVectorChunk import PhysicsVectorChunk
from classes.chunks.PhysicsInertiaMatrixChunk import PhysicsInertiaMatrixChunk
from classes.chunks.GameAttrChunks import GameAttrChunk, GameAttrColourParameterChunk, GameAttrFloatParameterChunk, GameAttrIntegerParameterChunk, GameAttrMatrixParameterChunk, GameAttrVectorParameterChunk
from classes.chunks.IntersectChunk import IntersectChunk
from classes.chunks.SurfaceTypeListChunk import SurfaceTypeListChunk

from classes.ChunkRegistry import ChunkRegistry

import data.chunkIdentifiers as chunkIdentifiers

#
# Default Chunk Registry
#

defaultChunkRegistry = ChunkRegistry()

defaultChunkRegistry.register(chunkIdentifiers.FENCE, FenceChunk)

defaultChunkRegistry.register(chunkIdentifiers.FENCE_2, Fence2Chunk)

defaultChunkRegistry.register(chunkIdentifiers.HISTORY, HistoryChunk)

defaultChunkRegistry.register(chunkIdentifiers.IMAGE, ImageChunk)

defaultChunkRegistry.register(chunkIdentifiers.IMAGE_DATA, ImageDataChunk)

defaultChunkRegistry.register(chunkIdentifiers.INDEX_LIST, IndexListChunk)

defaultChunkRegistry.register(chunkIdentifiers.MESH, MeshChunk)

defaultChunkRegistry.register(chunkIdentifiers.OLD_PRIMITIVE_GROUP, OldPrimitiveGroupChunk)

defaultChunkRegistry.register(chunkIdentifiers.PATH, PathChunk)

defaultChunkRegistry.register(chunkIdentifiers.POSITION_LIST, PositionListChunk)

defaultChunkRegistry.register(chunkIdentifiers.SHADER, ShaderChunk)

defaultChunkRegistry.register(chunkIdentifiers.SHADER_COLOUR_PARAMETER, ShaderColourParameterChunk)

defaultChunkRegistry.register(chunkIdentifiers.SHADER_FLOAT_PARAMETER, ShaderFloatParameterChunk)

defaultChunkRegistry.register(chunkIdentifiers.SHADER_INTEGER_PARAMETER, ShaderIntegerParameterChunk)

defaultChunkRegistry.register(chunkIdentifiers.SHADER_TEXTURE_PARAMETER, ShaderTextureParameterChunk)

defaultChunkRegistry.register(chunkIdentifiers.STATIC_ENTITY, StaticEntityChunk)

defaultChunkRegistry.register(chunkIdentifiers.TEXTURE, TextureChunk)

defaultChunkRegistry.register(chunkIdentifiers.UV_LIST, UVListChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLOUR_LIST, ColourListChunk)

defaultChunkRegistry.register(chunkIdentifiers.VERTEX_SHADER, VertexShaderChunk)

defaultChunkRegistry.register(chunkIdentifiers.BOUNDING_BOX, BoundingBoxChunk)

defaultChunkRegistry.register(chunkIdentifiers.BOUNDING_SPHERE, BoundingSphereChunk)

defaultChunkRegistry.register(chunkIdentifiers.STATIC_PHYS, StaticPhysChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_OBJECT, CollisionObjectChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_VOLUME, CollisionVolumeChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_ORIENTED_BOUNDING_BOX, CollisionOrientedBoundingBoxChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_CYLINDER, CollisionCylinderChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_SPHERE, CollisionSphereChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_VECTOR, CollisionVectorChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_OBJECT_ATTRIBUTE, CollisionObjectAttributeChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_EFFECT, CollisionEffectChunk)

defaultChunkRegistry.register(chunkIdentifiers.COLLISION_AXIS_ALIGNED_BOUNDING_BOX, CollisionAxisAlignedBoundingBoxChunk)

defaultChunkRegistry.register(chunkIdentifiers.RENDER_STATUS, RenderStatusChunk)
defaultChunkRegistry.register(chunkIdentifiers.INST_STAT_ENTITY, InstStatEntityChunk)

defaultChunkRegistry.register(chunkIdentifiers.INST_STAT_PHYS, InstStatPhysChunk)

defaultChunkRegistry.register(chunkIdentifiers.DYNA_PHYS, DynaPhysChunk)

defaultChunkRegistry.register(chunkIdentifiers.INSTANCE_LIST, InstanceListChunk)

defaultChunkRegistry.register(chunkIdentifiers.SCENEGRAPH, ScenegraphChunk)

defaultChunkRegistry.register(chunkIdentifiers.OLD_SCENEGRAPH_BRANCH, OldScenegraphBranchChunk)
defaultChunkRegistry.register(chunkIdentifiers.OLD_SCENEGRAPH_DRAWABLE, OldScenegraphDrawableChunk)
defaultChunkRegistry.register(chunkIdentifiers.OLD_SCENEGRAPH_ROOT, OldScenegraphRootChunk)
defaultChunkRegistry.register(chunkIdentifiers.OLD_SCENEGRAPH_SORT_ORDER, OldScenegraphSortOrderChunk)
defaultChunkRegistry.register(chunkIdentifiers.OLD_SCENEGRAPH_TRANSFORM, OldScenegraphTransformChunk)

defaultChunkRegistry.register(chunkIdentifiers.PHYSICS_OBJECT, PhysicsObjectChunk)

defaultChunkRegistry.register(chunkIdentifiers.PHYSICS_VECTOR, PhysicsVectorChunk)

defaultChunkRegistry.register(chunkIdentifiers.PHYSICS_INERTIA_MATRIX, PhysicsInertiaMatrixChunk)

defaultChunkRegistry.register(chunkIdentifiers.GAME_ATTR, GameAttrChunk)
defaultChunkRegistry.register(chunkIdentifiers.GAME_ATTRIBUTE_COLOUR_PARAMETER, GameAttrColourParameterChunk)
defaultChunkRegistry.register(chunkIdentifiers.GAME_ATTRIBUTE_FLOAT_PARAMETER, GameAttrFloatParameterChunk)
defaultChunkRegistry.register(chunkIdentifiers.GAME_ATTRIBUTE_INTEGER_PARAMETER, GameAttrIntegerParameterChunk)
defaultChunkRegistry.register(chunkIdentifiers.GAME_ATTRIBUTE_MATRIX_PARAMETER, GameAttrMatrixParameterChunk)
defaultChunkRegistry.register(chunkIdentifiers.GAME_ATTRIBUTE_VECTOR_PARAMETER, GameAttrVectorParameterChunk)

defaultChunkRegistry.register(chunkIdentifiers.INTERSECT, IntersectChunk)

defaultChunkRegistry.register(chunkIdentifiers.SURFACE_TYPE_LIST, SurfaceTypeListChunk)